// Domain glossary for software / IT / CS reading.
//
// Machine translation is generally fine for prose but drifts badly on
// technical nouns: "commit" becomes "cam kết", "thread" becomes "sợi chỉ",
// "socket" becomes "ổ cắm". Anything listed here wins over the machine
// translation, and the machine translation is still shown underneath as
// the general-English sense.
//
// Keys must be lowercase and already normalized (single spaces).

export const TECH_GLOSSARY = {
  // --- Roles & process -----------------------------------------------------
  developer: "lập trình viên; nhà phát triển phần mềm",
  "software developer": "lập trình viên phần mềm",
  "software engineer": "kỹ sư phần mềm",
  "web developer": "lập trình viên web",
  "frontend developer": "lập trình viên front-end",
  "front-end developer": "lập trình viên front-end",
  "backend developer": "lập trình viên back-end",
  "back-end developer": "lập trình viên back-end",
  "full-stack developer": "lập trình viên full-stack",
  "full stack developer": "lập trình viên full-stack",
  maintainer: "người bảo trì (dự án mã nguồn)",
  contributor: "người đóng góp (mã nguồn)",
  stakeholder: "bên liên quan; các bên có lợi ích trong dự án",
  "information technology": "công nghệ thông tin",
  "code review": "rà soát mã nguồn; review code",
  "pair programming": "lập trình cặp (hai người cùng viết trên một máy)",
  standup: "họp nhanh đầu ngày (daily standup)",
  sprint: "chu kỳ phát triển ngắn (sprint, thường 1–2 tuần)",
  backlog: "danh sách công việc tồn đọng (backlog)",
  retrospective: "buổi nhìn lại cuối sprint (retrospective)",
  onboarding: "quá trình làm quen / tiếp nhận (người mới, hệ thống mới)",
  handoff: "bàn giao (công việc, trách nhiệm)",
  "postmortem": "báo cáo phân tích sự cố sau khi khắc phục",
  "on-call": "trực hệ thống (sẵn sàng xử lý sự cố)",
  "technical debt": "nợ kỹ thuật (chất lượng đánh đổi để làm nhanh)",
  "tech debt": "nợ kỹ thuật",
  "scope creep": "phình phạm vi (yêu cầu bị nới rộng dần)",

  // --- Version control -----------------------------------------------------
  commit: "commit — bản ghi thay đổi trong Git",
  "pull request": "yêu cầu gộp mã (pull request)",
  "merge request": "yêu cầu gộp mã (merge request)",
  merge: "gộp (nhánh mã nguồn)",
  rebase: "rebase — dựng lại lịch sử commit lên nhánh khác",
  branch: "nhánh (mã nguồn)",
  fork: "fork — bản sao độc lập của kho mã; (hệ điều hành) tạo tiến trình con",
  repository: "kho lưu trữ mã nguồn (repo)",
  repo: "kho mã nguồn",
  "cherry-pick": "cherry-pick — lấy riêng một commit sang nhánh khác",
  "squash": "gộp nhiều commit thành một",
  staging: "vùng chờ (git); môi trường thử nghiệm trước khi lên production",
  checkout: "chuyển sang (nhánh / phiên bản mã)",
  diff: "khác biệt giữa hai phiên bản mã",
  conflict: "xung đột (khi gộp mã)",
  "revert": "hoàn tác (một thay đổi đã commit)",
  tag: "thẻ đánh dấu (phiên bản); thẻ HTML",

  // --- Core programming ----------------------------------------------------
  argument: "đối số (giá trị truyền vào hàm)",
  parameter: "tham số (biến khai báo trong hàm)",
  variable: "biến",
  constant: "hằng số",
  scope: "phạm vi (của biến); phạm vi công việc",
  closure: "closure — hàm giữ lại biến ở phạm vi bao ngoài",
  callback: "hàm gọi lại (callback)",
  "higher-order function": "hàm bậc cao (nhận hoặc trả về hàm khác)",
  "pure function": "hàm thuần khiết (không gây tác dụng phụ)",
  "side effect": "tác dụng phụ (thay đổi trạng thái ngoài hàm)",
  idempotent: "bất biến khi lặp lại (gọi nhiều lần cho cùng kết quả)",
  recursion: "đệ quy",
  iteration: "vòng lặp; lần lặp",
  statement: "câu lệnh",
  expression: "biểu thức",
  assignment: "phép gán",
  declaration: "khai báo",
  signature: "chữ ký hàm (tên, tham số, kiểu trả về)",
  overload: "nạp chồng (nhiều hàm cùng tên, khác tham số)",
  override: "ghi đè (phương thức lớp cha)",
  inheritance: "kế thừa",
  encapsulation: "đóng gói (che giấu chi tiết bên trong)",
  polymorphism: "đa hình",
  abstraction: "trừu tượng hoá",
  instance: "thể hiện (một đối tượng cụ thể của lớp)",
  "instantiate": "khởi tạo (một đối tượng)",
  property: "thuộc tính",
  attribute: "thuộc tính",
  method: "phương thức (hàm thuộc về đối tượng)",
  interface: "giao diện lập trình (interface); giao diện",
  implementation: "phần cài đặt (mã thực thi cụ thể)",
  "implement": "cài đặt; triển khai (một chức năng)",
  boilerplate: "mã khuôn mẫu lặp lại",
  refactor: "tái cấu trúc mã (không đổi hành vi)",
  deprecated: "không còn được khuyến nghị dùng (sẽ bị loại bỏ)",
  legacy: "cũ, kế thừa từ trước (hệ thống/mã cũ)",
  wrapper: "lớp bao (bọc ngoài để dùng tiện hơn)",
  helper: "hàm/tiện ích hỗ trợ",
  utility: "tiện ích",
  snippet: "đoạn mã ngắn",
  "syntactic sugar": "cú pháp cho gọn (không thêm khả năng mới)",
  "type": "kiểu (dữ liệu)",
  "cast": "ép kiểu",
  "immutable": "bất biến (không thể sửa sau khi tạo)",
  "mutable": "có thể thay đổi",
  "mutation": "sự thay đổi trạng thái tại chỗ",
  "literal": "giá trị viết trực tiếp trong mã (literal)",
  "escape": "thoát ký tự (escape)",
  "parse": "phân tích cú pháp; bóc tách dữ liệu",
  "parser": "bộ phân tích cú pháp",
  "compile": "biên dịch",
  "compiler": "trình biên dịch",
  "interpreter": "trình thông dịch",
  "runtime": "thời điểm chạy; môi trường chạy",
  "build": "quá trình dựng bản phần mềm; bản dựng",
  "linter": "công cụ kiểm tra lỗi/phong cách mã",
  "dependency": "phụ thuộc (thư viện mà mã cần)",
  "dependencies": "các thư viện phụ thuộc",
  "package": "gói phần mềm",
  "library": "thư viện",
  "framework": "khung phát triển (framework)",
  "module": "mô-đun",
  "namespace": "không gian tên",
  "binding": "liên kết (giữa tên và giá trị / giữa hai hệ thống)",
  "hook": "hook — điểm móc để chèn xử lý riêng",
  "middleware": "middleware — lớp xử lý trung gian",
  "plugin": "phần mở rộng (plugin)",
  "flag": "cờ (tuỳ chọn bật/tắt)",
  "feature flag": "cờ tính năng (bật/tắt tính năng khi đang chạy)",
  "toggle": "công tắc bật/tắt",
  "stub": "hàm giả lập rỗng (stub)",
  "mock": "đối tượng giả lập dùng khi kiểm thử",
  "fixture": "dữ liệu mẫu chuẩn bị sẵn cho test",
  "assertion": "khẳng định kiểm tra trong test",
  "test suite": "bộ kiểm thử",
  "regression": "lỗi tái phát (chức năng từng chạy nay hỏng)",
  "edge case": "trường hợp biên hiếm gặp",
  "corner case": "trường hợp hiếm do nhiều điều kiện gặp nhau",
  "coverage": "độ bao phủ (của kiểm thử)",
  "benchmark": "phép đo hiệu năng chuẩn",
  "profiling": "đo/phân tích hiệu năng khi chạy",
  "bottleneck": "điểm nghẽn hiệu năng",
  "overhead": "chi phí phát sinh thêm (bộ nhớ, thời gian)",
  "throughput": "thông lượng (lượng xử lý mỗi đơn vị thời gian)",
  "latency": "độ trễ",
  "bug": "lỗi phần mềm",
  "patch": "bản vá",
  "hotfix": "bản vá khẩn",
  "workaround": "cách khắc phục tạm",
  "root cause": "nguyên nhân gốc rễ",
  "stack trace": "vết ngăn xếp lỗi (danh sách hàm khi lỗi xảy ra)",
  "traceback": "vết truy ngược lỗi",
  "breakpoint": "điểm dừng khi gỡ lỗi",
  "debug": "gỡ lỗi",
  "log": "nhật ký chạy; ghi nhật ký",
  "verbose": "chi tiết, dài dòng (mức ghi log)",

  // --- Data & memory -------------------------------------------------------
  "array": "mảng",
  "list": "danh sách",
  "queue": "hàng đợi",
  "stack": "ngăn xếp; tập công nghệ (tech stack)",
  "heap": "vùng nhớ heap; cấu trúc heap",
  "hash": "băm; giá trị băm",
  "hash map": "bảng băm",
  "key": "khoá (định danh); khoá mã hoá",
  "value": "giá trị",
  "pointer": "con trỏ",
  "reference": "tham chiếu",
  "allocation": "cấp phát (bộ nhớ)",
  "garbage collection": "thu gom rác (giải phóng bộ nhớ tự động)",
  "memory leak": "rò rỉ bộ nhớ",
  "buffer": "vùng đệm",
  "cache": "bộ nhớ đệm (cache)",
  "payload": "phần dữ liệu chính (được gửi đi)",
  "schema": "lược đồ cấu trúc dữ liệu",
  "query": "truy vấn",
  "index": "chỉ mục (giúp tra cứu nhanh)",
  "record": "bản ghi",
  "row": "hàng (bản ghi trong bảng)",
  "column": "cột (trường trong bảng)",
  "transaction": "giao dịch (nhóm thao tác toàn-bộ-hoặc-không)",
  "rollback": "quay lui về trạng thái trước",
  "migration": "chuyển đổi cấu trúc dữ liệu (migration)",
  "seed": "dữ liệu khởi tạo; giá trị mầm ngẫu nhiên",
  "serialization": "tuần tự hoá (chuyển dữ liệu thành chuỗi/byte)",
  "deserialize": "giải tuần tự hoá",
  "encoding": "mã hoá ký tự / định dạng",
  "checksum": "mã kiểm tra tính toàn vẹn",
  "snapshot": "ảnh chụp trạng thái tại một thời điểm",
  "backup": "bản sao lưu",
  "replication": "nhân bản dữ liệu sang máy khác",
  "shard": "mảnh dữ liệu (chia nhỏ để mở rộng)",

  // --- Concurrency ---------------------------------------------------------
  "thread": "luồng (đơn vị thực thi); chuỗi thảo luận",
  "process": "tiến trình; quy trình",
  "concurrency": "tính đồng thời (nhiều việc xen kẽ)",
  "parallelism": "tính song song (nhiều việc chạy cùng lúc)",
  "race condition": "lỗi tranh chấp thứ tự thực thi",
  "deadlock": "khoá chết (các bên chờ lẫn nhau)",
  "lock": "khoá (chặn truy cập đồng thời)",
  "mutex": "khoá loại trừ lẫn nhau (mutex)",
  "atomic": "nguyên tử (không thể bị chen ngang giữa chừng)",
  "blocking": "chặn (dừng chờ cho tới khi xong)",
  "non-blocking": "không chặn (không phải dừng chờ)",
  "asynchronous": "bất đồng bộ",
  "synchronous": "đồng bộ (chờ xong mới đi tiếp)",
  "poll": "hỏi định kỳ (polling)",
  "polling": "hỏi định kỳ để kiểm tra trạng thái",
  "throttle": "giới hạn tần suất gọi",
  "debounce": "gộp các lần gọi liên tiếp thành một",
  "backpressure": "áp lực ngược (khi nơi nhận xử lý không kịp)",
  "worker": "tiến trình/luồng làm việc nền",
  "job": "tác vụ (được xếp hàng chờ chạy)",
  "scheduler": "bộ lập lịch",
  "spawn": "sinh ra (tiến trình/luồng mới)",

  // --- Web / network -------------------------------------------------------
  "request": "yêu cầu (gửi tới máy chủ)",
  "response": "phản hồi (từ máy chủ)",
  "endpoint": "điểm cuối API (đường dẫn nhận yêu cầu)",
  "socket": "socket — đầu nối mạng giữa hai chương trình",
  "port": "cổng (mạng); chuyển đổi phần mềm sang nền tảng khác",
  "host": "máy chủ; máy đăng cai chạy dịch vụ",
  "client": "phía người dùng / máy khách",
  "server": "máy chủ",
  "proxy": "máy chủ trung gian (proxy)",
  "gateway": "cổng vào hệ thống (gateway)",
  "load balancer": "bộ cân bằng tải",
  "bandwidth": "băng thông",
  "timeout": "hết thời gian chờ",
  "retry": "thử lại",
  "rate limit": "giới hạn số lần gọi trong một khoảng thời gian",
  "header": "phần đầu (thông tin kèm theo yêu cầu/phản hồi)",
  "cookie": "cookie — dữ liệu nhỏ trình duyệt lưu cho trang web",
  "session": "phiên làm việc",
  "token": "mã thông báo (dùng để xác thực)",
  "authentication": "xác thực (bạn là ai)",
  "authorization": "phân quyền (bạn được làm gì)",
  "credentials": "thông tin đăng nhập",
  "permission": "quyền truy cập; sự cho phép",
  "permissions": "các quyền truy cập",
  "encryption": "mã hoá",
  "hashing": "băm mật khẩu/dữ liệu (một chiều)",
  "certificate": "chứng chỉ số",
  "vulnerability": "lỗ hổng bảo mật",
  "exploit": "cách khai thác lỗ hổng",
  "sanitize": "làm sạch dữ liệu đầu vào (chống tấn công)",
  "validate": "kiểm tra tính hợp lệ",
  "throttling": "hạn chế tốc độ truy cập",
  "webhook": "webhook — máy chủ tự gọi ngược lại URL của bạn khi có sự kiện",
  "polyfill": "mã bù tính năng cho trình duyệt cũ",
  "render": "kết xuất/vẽ ra giao diện",
  "hydration": "gắn lại tương tác vào HTML dựng sẵn (hydration)",
  "viewport": "vùng nhìn thấy của màn hình",
  "responsive": "tự co giãn theo kích thước màn hình",
  "accessibility": "khả năng tiếp cận (cho người khuyết tật)",
  "throttled": "bị giới hạn tốc độ",

  // --- Ops / infra ---------------------------------------------------------
  "deploy": "triển khai (đưa mã lên môi trường chạy)",
  "deployment": "việc triển khai; bản triển khai",
  "release": "phát hành (phiên bản)",
  "rollout": "tung ra dần cho người dùng",
  "production": "môi trường thật (người dùng đang dùng)",
  "environment": "môi trường (chạy phần mềm)",
  "pipeline": "chuỗi bước tự động (build → test → deploy)",
  "container": "container — gói ứng dụng chạy độc lập",
  "image": "ảnh container (bản đóng gói để chạy)",
  "orchestration": "điều phối nhiều container/dịch vụ",
  "provisioning": "cấp phát hạ tầng/tài nguyên",
  "scaling": "mở rộng quy mô hệ thống",
  "downtime": "thời gian ngừng hoạt động",
  "uptime": "thời gian hoạt động liên tục",
  "outage": "sự cố ngừng dịch vụ",
  "incident": "sự cố",
  "monitoring": "giám sát hệ thống",
  "observability": "khả năng quan sát hệ thống từ bên trong",
  "alert": "cảnh báo",
  "failover": "tự chuyển sang hệ thống dự phòng khi hỏng",
  "redundancy": "dự phòng (nhân đôi để chống hỏng)",
  "resilience": "khả năng chịu lỗi và phục hồi",
  "quota": "hạn mức được cấp",
  "provision": "cấp phát (tài nguyên)",
  "cron": "lịch chạy tự động định kỳ (cron)",
  "daemon": "tiến trình chạy ngầm",
  "firmware": "phần mềm nhúng trong thiết bị",
  "sandbox": "môi trường cách ly an toàn",
  "boilerplate project": "dự án mẫu dựng sẵn",

  // --- Docs / general tech English -----------------------------------------
  "documentation": "tài liệu hướng dẫn",
  "docs": "tài liệu",
  "specification": "đặc tả (mô tả yêu cầu chi tiết)",
  "spec": "bản đặc tả",
  "changelog": "nhật ký thay đổi phiên bản",
  "readme": "tệp giới thiệu/hướng dẫn dự án",
  "issue": "vấn đề/phiếu báo lỗi được ghi nhận",
  "ticket": "phiếu công việc",
  "milestone": "cột mốc",
  "roadmap": "lộ trình phát triển",
  "prerequisite": "điều kiện cần có trước",
  "prerequisites": "các yêu cầu cần có trước",
  "constraint": "ràng buộc",
  "trade-off": "sự đánh đổi",
  "tradeoff": "sự đánh đổi",
  "caveat": "lưu ý/cảnh báo kèm theo",
  "gotcha": "cái bẫy dễ mắc phải",
  "pitfall": "sai lầm thường gặp",
  "workflow": "luồng công việc",
  "throughput rate": "tốc độ xử lý",
  "granularity": "độ chi tiết/mịn",
  "verbosity": "mức độ chi tiết (của log)",
  "arbitrary": "tuỳ ý, bất kỳ (không theo quy tắc cố định)",
  "deterministic": "tất định (cùng đầu vào luôn cho cùng kết quả)",
  "heuristic": "phương pháp ước lượng theo kinh nghiệm",
  "canonical": "chuẩn mực, dạng chính thức được chọn",
  "explicit": "tường minh, nói rõ ra",
  "implicit": "ngầm định, không nói rõ",
  "leverage": "tận dụng",
  "seamless": "liền mạch, không gợn",
  "robust": "vững chắc, chịu lỗi tốt",
  "graceful": "êm ái (xử lý lỗi mà không sập)",
  "gracefully": "một cách êm ái, có kiểm soát",
  "fallback": "phương án dự phòng khi cách chính thất bại",
  "opt-in": "phải bật thủ công mới có",
  "opt-out": "mặc định bật, muốn tắt phải tự chọn",
  "out of the box": "dùng được ngay, không cần cấu hình",
  "under the hood": "bên trong cơ chế hoạt động",
  "state of the art": "tiên tiến nhất hiện nay",
  "best practice": "cách làm tốt nhất được khuyến nghị",
  "anti-pattern": "cách làm sai thường gặp (nên tránh)",
  "design pattern": "mẫu thiết kế",
  "abstraction layer": "lớp trừu tượng",
  "backward compatible": "tương thích ngược (bản cũ vẫn chạy được)",
  "breaking change": "thay đổi phá vỡ tương thích",
  "boundary": "ranh giới (giữa các thành phần)",
  "throughput limit": "giới hạn năng lực xử lý",
  "overhead cost": "chi phí phát sinh",
  "trailing": "ở cuối, đứng sau (ký tự/khoảng trắng cuối)",
  "leading": "ở đầu, đứng trước",
  "nested": "lồng nhau",
  "inline": "nội tuyến (đặt ngay tại chỗ)",
  "toggleable": "có thể bật/tắt",
  "seamlessly": "một cách liền mạch",
  "stale": "cũ, đã lỗi thời (dữ liệu/cache)",
  "dirty": "đã bị sửa, chưa lưu (trạng thái)",
  "idle": "rảnh, không hoạt động",
  "spike": "tăng vọt đột ngột (tải/lưu lượng)",
  "drift": "trôi lệch dần khỏi trạng thái mong muốn",
  "orphan": "bị bỏ rơi, không còn ai tham chiếu tới",
  "dangling": "treo lơ lửng (tham chiếu tới thứ đã bị xoá)"
};

/** Terms whose tech meaning differs so sharply from everyday English that we
 *  always want to show the general-English translation too. */
export const AMBIGUOUS_TECH_TERMS = new Set([
  "commit", "thread", "socket", "port", "fork", "branch", "stack", "heap",
  "cache", "key", "value", "tag", "image", "container", "scope", "instance",
  "property", "interface", "type", "cast", "flag", "hook", "mock", "stale",
  "dirty", "idle", "spike", "drift", "orphan", "dangling", "escape", "seed",
]);
